export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  CUSTOMER_APP_CMS: "/customer-app-cms",
  CENTRAL_WAREHOUSE: "/central-warehouse",
  CENTRAL_WAREHOUSE_PRODUCTS: "/central-warehouse/products",
  SUB_HUB_NETWORK: "/sub-hub-network",
  SUB_HUB_ADD: "/sub-hub-network/add",
  HUB_INVENTORY: "/sub-hub-network/inventory",
  HUB_REQUISITIONS: "/sub-hub-network/requisitions",
  HUB_TRANSFERS: "/sub-hub-network/transfers",
  HUB_DISPATCH_LOGS: "/sub-hub-network/dispatch-logs",
  USER_MANAGEMENT: "/user-management",
  USER_MANAGEMENT_CUSTOMERS: "/user-management/customers",
  LOGISTICS: "/logistics",
  FINANCE_PAYMENTS: "/finance-payments",
  CUSTOMER_EXECUTIVE: "/customer-executive",
  CUSTOMER_EXECUTIVE_CUSTOMERS: "/customer-executive/customers",
  CUSTOMER_EXECUTIVE_ORDERS: "/customer-executive/orders",
  CUSTOMER_EXECUTIVE_PAYMENTS: "/customer-executive/payments",
  CUSTOMER_EXECUTIVE_TRACKING: "/customer-executive/tracking",
  CUSTOMER_EXECUTIVE_COMPLAINTS: "/customer-executive/complaints",
  CUSTOMER_EXECUTIVE_CUSTOMERS_NEW: "/customer-executive/customers/new",
  CUSTOMER_EXECUTIVE_ORDERS_NEW: "/customer-executive/orders/new",
  USER_MANAGEMENT_CUSTOMER_EXECUTIVES: "/user-management/customer-executives",
  CUSTOMER_EXECUTIVE_ADD: "/user-management/customer-executives/add",
  SUB_HUB_MANAGERS: "/user-management/sub-hub-managers",
  SUB_HUB_MANAGER_ADD: "/user-management/sub-hub-managers/add",
  USER_MANAGEMENT_DRIVERS: "/user-management/drivers",
  APPROVALS_CENTER: "/approvals",
  USER_ONBOARDING: "/user-management/onboarding",
  ANALYTICS_REPORTS: "/analytics-reports",
  SYSTEM_SETTINGS: "/system-settings",
  PURCHASE_ORDERS: "/central-warehouse",
  ORDERS: "/orders",
  NOTIFICATION_CENTER: "/notification-center",
  CUSTOMERS: "/customer-executive",
  MANAGERS: "/user-management",
  UNAUTHORIZED: "/unauthorized",
  FORBIDDEN: "/forbidden",
} as const;

export const GUEST_ROUTES = [ROUTES.LOGIN] as const;

export const PROTECTED_ROUTES = [
  ROUTES.DASHBOARD,
  ROUTES.CUSTOMER_APP_CMS,
  ROUTES.CENTRAL_WAREHOUSE,
  ROUTES.SUB_HUB_NETWORK,
  ROUTES.USER_MANAGEMENT,
  ROUTES.ORDERS,
  ROUTES.NOTIFICATION_CENTER,
  ROUTES.LOGISTICS,
  ROUTES.FINANCE_PAYMENTS,
  ROUTES.CUSTOMER_EXECUTIVE,
  ROUTES.APPROVALS_CENTER,
  ROUTES.ANALYTICS_REPORTS,
  ROUTES.SYSTEM_SETTINGS,
] as const;
